<?php
// ============================================
// seed_universities.php
// Run this ONCE to fill your database with
// university data generated by OpenAI.
// Open in browser: http://localhost/qapp-backend/scripts/seed_universities.php
// ============================================

require_once '../config/db.php';

// -----------------------------------------------
// PUT YOUR OPENAI API KEY HERE
// -----------------------------------------------
$OPENAI_API_KEY = "sk-your-openai-key-here";
// -----------------------------------------------

$universities = [
    "Nazarbayev University Astana Kazakhstan",
    "Kazakh-British Technical University KBTU Almaty Kazakhstan",
    "Astana IT University AITU Kazakhstan",
    "KIMEP University Almaty Kazakhstan",
    "SDU Suleyman Demirel University Kaskelen Kazakhstan",
    "Al-Farabi Kazakh National University KazNU Almaty Kazakhstan"
];

function callOpenAI($api_key, $uni_name) {
    $prompt = "Generate a detailed university profile for: $uni_name

Return ONLY valid JSON with exactly this structure, no extra text:
{
  \"name\": \"English name\",
  \"name_ru\": \"Russian name\",
  \"city\": \"city name\",
  \"country\": \"Kazakhstan\",
  \"founded\": 2000,
  \"type\": \"Research or Technical or Teaching or Liberal Arts\",
  \"languages\": \"English or Russian or Kazakh or combination\",
  \"total_programs\": 30,
  \"min_gpa\": 3.5,
  \"min_ielts\": 6.0,
  \"min_sat\": 1100,
  \"application_deadline\": \"2026-06-01\",
  \"website\": \"https://website.kz\",
  \"email\": \"admissions@website.kz\",
  \"description\": \"2-3 sentence description\",
  \"programs\": [
    {\"name\": \"program name\", \"field\": \"Computer Science or Engineering or Business or Science or Humanities\", \"degree\": \"Bachelor\", \"duration\": 4, \"language\": \"English\"}
  ],
  \"scholarships\": [
    {\"name\": \"scholarship name\", \"description\": \"short description\", \"covers\": \"100% tuition\", \"eligibility\": \"GPA 4.0+\", \"min_gpa\": 4.0, \"min_ielts\": 6.5}
  ],
  \"deadlines\": [
    {\"label\": \"Application Opens\", \"date\": \"2026-01-15\"},
    {\"label\": \"Final Deadline\", \"date\": \"2026-06-01\"},
    {\"label\": \"Admission Decision\", \"date\": \"2026-07-15\"}
  ]
}

Include 5-7 real programs. Use real data where you know it.";

    $payload = json_encode([
        "model"    => "gpt-4o-mini",
        "messages" => [
            ["role" => "system", "content" => "You are a university data assistant. Always respond with valid JSON only, no markdown."],
            ["role" => "user",   "content" => $prompt]
        ],
        "max_tokens"  => 1500,
        "temperature" => 0.2
    ]);

    $ch = curl_init("https://api.openai.com/v1/chat/completions");
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        "Content-Type: application/json",
        "Authorization: Bearer $api_key"
    ]);

    $response = curl_exec($ch);
    curl_close($ch);

    $decoded = json_decode($response, true);
    $text    = $decoded['choices'][0]['message']['content'] ?? '';
    $text    = preg_replace('/```json|```/', '', $text);
    return json_decode(trim($text), true);
}

function saveUniversity($conn, $data) {
    // Insert university
    $stmt = mysqli_prepare($conn, "INSERT INTO universities (name, name_ru, city, country, founded, type, languages, total_programs, min_gpa, min_ielts, min_sat, application_deadline, website, email, description) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
    mysqli_stmt_bind_param($stmt, "ssssissiddisss",
        $data['name'], $data['name_ru'], $data['city'], $data['country'],
        $data['founded'], $data['type'], $data['languages'], $data['total_programs'],
        $data['min_gpa'], $data['min_ielts'], $data['min_sat'],
        $data['application_deadline'], $data['website'], $data['email'], $data['description']
    );
    mysqli_stmt_execute($stmt);
    $uni_id = mysqli_insert_id($conn);

    // Insert programs
    foreach ($data['programs'] as $prog) {
        $s = mysqli_prepare($conn, "INSERT INTO programs (university_id, name, field, degree, duration, language) VALUES (?,?,?,?,?,?)");
        mysqli_stmt_bind_param($s, "issssi", $uni_id, $prog['name'], $prog['field'], $prog['degree'], $prog['duration'], $prog['language']);
        mysqli_stmt_execute($s);
    }

    // Insert scholarships
    foreach ($data['scholarships'] as $sch) {
        $s = mysqli_prepare($conn, "INSERT INTO scholarships (university_id, name, description, covers, eligibility, min_gpa, min_ielts) VALUES (?,?,?,?,?,?,?)");
        mysqli_stmt_bind_param($s, "issssdd", $uni_id, $sch['name'], $sch['description'], $sch['covers'], $sch['eligibility'], $sch['min_gpa'], $sch['min_ielts']);
        mysqli_stmt_execute($s);
    }

    // Insert deadlines
    foreach ($data['deadlines'] as $dead) {
        $s = mysqli_prepare($conn, "INSERT INTO deadlines (university_id, label, date) VALUES (?,?,?)");
        mysqli_stmt_bind_param($s, "iss", $uni_id, $dead['label'], $dead['date']);
        mysqli_stmt_execute($s);
    }

    return $uni_id;
}

// Clear existing data before seeding
mysqli_query($conn, "DELETE FROM deadlines");
mysqli_query($conn, "DELETE FROM scholarships");
mysqli_query($conn, "DELETE FROM programs");
mysqli_query($conn, "DELETE FROM universities");
mysqli_query($conn, "ALTER TABLE universities AUTO_INCREMENT = 1");

echo "<h2>Seeding universities...</h2>";

foreach ($universities as $uni_name) {
    echo "<p>Processing: <strong>$uni_name</strong>... ";
    flush();

    $data = callOpenAI($OPENAI_API_KEY, $uni_name);

    if (!$data) {
        echo "<span style='color:red'>FAILED - could not parse AI response</span></p>";
        continue;
    }

    $id = saveUniversity($conn, $data);
    echo "<span style='color:green'>SAVED (id: $id)</span></p>";
    flush();

    sleep(1); // avoid hitting rate limits
}

echo "<h2 style='color:green'>Done! All universities saved to database.</h2>";
mysqli_close($conn);
?>
